#!/bin/bash

# hostdestroy
#
# This file is run on the host, and can be used to do things like
# destroy docker volumes (e.g. docker volume rm dr-helloworld-configvol )
#
#

SERVICENAME="$1"
IMAGENAME="$2"

echo "dr-helloworld destroy completed successfully."
