#!/bin/bash

SERVICENAME="$1"
IMAGENAME="$2"

# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run -i -t --name="${SERVICENAME}-enter" -h "${HOSTNAME}"     \
               -v "dr-${SERVICENAME}-config:/config"                   \
               ${IMAGENAME} helloworld ${SERVICENAME} ${IMAGENAME}
docker rm "${SERVICENAME}-enter"