#!/bin/bash

# Service name passed as argument by dr.
SERVICENAME="$1"
IMAGENAME="$2"

cat <<EOF >&2
   
NAME
   ${SERVICENAME} - says hello world! Yay!
       
SYNOPSIS
   ${SERVICENAME} help      - This help
   ${SERVICENAME} run       - Make it go!
   
DESCRIPTION
   A friendly example. Built from ${IMAGENAME}.
EOF