#!/bin/bash

# Read in the name of the service. This is set by the user at install time.
# dr creates the servicename.txt file for us.
SERVICENAME=$(</dr/txt/servicename.txt)

cat <<EOF >&2
   
NAME
   dr ${SERVICENAME} - says hello world! Yay!
   
SYNOPSIS
   dr ${SERVICENAME} help      - This help
   dr ${SERVICENAME} run       - Make it go!
   
DESCRIPTION
   A friendly example.
EOF