#!/bin/bash

# Service name passed as argument by dr.
SERVICENAME="$1"

cat <<EOF >&2
   
NAME
   dr ${SERVICENAME} - says hello world! Yay!
   
SYNOPSIS
   dr ${SERVICENAME} help      - This help
   dr ${SERVICENAME} run       - Make it go!
   
DESCRIPTION
   A friendly example.
EOF