#!/bin/bash

# hostinit
#
# This file is run on the host, and can be used to do things like
# set up docker volumes (e.g. docker volume create dr-helloworld-configvol )
#
#

SERVICENAME="$1"

echo "hostinit completed successfully."
