#!/bin/bash

SERVICENAME="$1"
CONTAINERNAME="$2"

# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run --rm -i -t --name="${SERVICENAME}-run" -h "${HOSTNAME}" \
               ${CONTAINERNAME} /usr/local/bin/helloworld ${SERVICENAME} ${CONTAINERNAME}
