#!/bin/bash

SERVICENAME="$1"
IMAGENAME="$2"

# This script is run inside the container by the script "run" on the host.

cat <<EOF
                 ,.     ,.
                {^ \-"-/ ^}
                "   """   "
               { <O> _ <O> }
               ==_ .:Y:. _==
             .""  `--^--' "".
            (,~-~."" "" ,~-~.)
      ------(     )----(     )-----
            ^-'-'-^    ^-'-'-^
      _____________________________
            |"""" /~.^.~\ """"|
             ,i-i-i(""(  i-i-i.
            (o o o ))"")( o o o)
             \(_) /(""(  \ (_)/
              `--'  \""\  `--'
                     )"")
                    (""/
                     `"
                     
    Hello world!
    I'm $SERVICENAME
    Based on $IMAGENAME

EOF
