#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# SERVICENAME and IMAGENAME are provided by _variables.
cat <<EOF >&2
   
NAME
   ${SERVICENAME} - says hello world! Yay!
       
SYNOPSIS
   ${SERVICENAME} help      - This help
   ${SERVICENAME} run       - Make it go!
   
DESCRIPTION
   A friendly example. Built from ${IMAGENAME}.
EOF