#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# This script is run on the host.
# It launches the docker container and runs our hello world command.

# Run the service. Can't use --rm as we don't want volumes cleared.
# DOCKEROPTS, SERVICENAME AND IMAGENAME are set by _variables.
docker run -i -t --name="${SERVICENAME}-run" -h "${HOSTNAME}"           \
               ${DOCKEROPTS[@]}  ${IMAGENAME}                           \
               helloworld ${SERVICENAME} ${IMAGENAME}
RVAL=$?
docker rm "${SERVICENAME}-run" >/dev/null 2>&1
exit "$RVAL"
