# drunner service configuration for helloworld
#
---
configuration:
   SECRETWORD:
      description: "The secret word to use."
      default: "squirrel"
      type: string

volumes:

containers:
   - drunner/helloworld

commands:
   run:
      - result=run("docker run --rm -e SECRETWORD=${SECRETWORD} ${IMAGENAME} helloworld ${SERVICENAME} ${IMAGENAME}")
      - if result~=0 then
            print("Failed to run helloworld.")
         else
            print("I ran helloworld! Yeah")
         end

   stop:
      - print("What?")

help: |
   NAME
      ${SERVICENAME}

   SYNOPSIS
      ${SERVICENAME} help
         This help.

      ${SERVICENAME} run
         Say hello to the world.

      ${SERVICENAME} configure SECRETWORD
         Set the secret word.

   DESCRIPTION
      A simple dRunner example. Built from ${IMAGENAME}.
