# drunner service configuration for helloworld
#
---
configuration:
   SECRETWORD:
      description: "The secret word to use."
      default: "squirrel"
      type: string
   PUBLICWORD:
      description: "A word for everyone"
      required: true

volumes:
   dave-${SERVICENAME}:
      manage: false
      backup: false
   steve-${SERVICENAME}:
      manage: false
      backup: false

containers:
   - drunner/helloworld

commands:
   run:
      - docker run --rm -e SECRETWORD=${SECRETWORD} ${IMAGENAME} helloworld ${SERVICENAME} ${IMAGENAME}

   stop:
      - print "What?"

help: |
   NAME
      ${SERVICENAME}

   SYNOPSIS
      ${SERVICENAME} help
         This help.

      ${SERVICENAME} run
         Say hello to the world.

      ${SERVICENAME} configure SECRETWORD
         Set the secret word.

   DESCRIPTION
      A simple dRunner example. Built from ${IMAGENAME}.
